### ISSUE TITLE
Reset: false not working?

### ISSUE THREAD

**Issue by ryandc** [xtianmiller/emergence.js#1]
Hey there,

I've specified in the settings reset:false, but the emergence status is still resetting after it's left the viewport. I'm using Chrome version 56.0.2924.87, and it's happening in 2 separate projects.

Any clues as to what might be causing this?

Code below:

(function($, document) {

    var six_inview = {

        on_ready: function() {
            six_inview.initEmergence();
        },

        initEmergence: function() {
            emergence.init({
                reset: false
            });
        },
    }

    $(document).ready( six_inview.on_ready );
}(jQuery, document));

**Comment by xtianmiller** [comment]
Hi,
Thanks for your feedback. There was an overlooked issue where reset false and true were actually doing the opposite. Should be resolved now in v1.0.4.

**Comment by ryandc** [comment]
Brilliant 👍
