### ISSUE TITLE
Use native Intersection Observer

### ISSUE THREAD

**Issue by johanneslamers** [xtianmiller/emergence.js#10]
Would be nice to make use of the native Intersection Observer API. 

https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

**Comment by xtianmiller** [comment]
@johanneslamers This is definitely something we'll keep an eye on moving forward as support gets better—while it's shipped in most modern browsers you need a polyfill for better support.

**Comment by mjsisley** [comment]
Perhaps you could use Intersection Observer for browsers that have support and use the current implementation as a fallback?
