### ISSUE TITLE
Per-item options

### ISSUE THREAD

**Issue by kyds3k** [xtianmiller/emergence.js#11]
Would be nice to be able to define the options on an individual element. For instance, you might want one element to grow when it's 50% visible, and some other to only react when it's 60% visible.

**Comment by mikestempien** [comment]
+1

**Comment by xtianmiller** [comment]
@kyds3k Great idea and will look into this when I get time. It would come down to adding some of the options as additional data-attributes that you could customize per item, otherwise would resort to the global default.
