### ISSUE TITLE
Trigger animation when div is visible

### ISSUE THREAD

**Issue by FlatAutumn** [xtianmiller/emergence.js#12]
I have a little paper plane and want to satrt its animation qhen the div enters de viewport. This is what i have in the css: 
@keyframes example {
        0%   {left:0%; top:75%;}
        25%  {left:25%; top:75%;}
	50%  {left:75%; top:75%;}
	100% {left:100%; top:75%;}
}
						
.target[data-emergence=visible] {
        animation-name: example;
        animation-duration: 5s
}

Do i have to attach this to the div or to the image i want to animate?

**Comment by xtianmiller** [comment]
Hey @FlatAutumn, I'd need to see more of the code to determine how you want to render the animation, can you provide some of the HTML—are you also able to confirm that the script is set up correctly and changing the state to visible when through dev tools?

**Comment by FlatAutumn** [comment]
Dont worry, i figured it out. It was a little mistake i didnt see xD
Thanks anyways :)
