### ISSUE TITLE
Watched elements not visible when scrolled to on mobile

### ISSUE THREAD

**Issue by ElliGator** [xtianmiller/emergence.js#4]
Hi, thanks for the awesome plugin. I found an issue where I have data-emergence="hidden" on my watched element and works fine on desktop. However, on mobile (Android OS) the elements are not being revealed like they are on desktop, they stay hidden.

**Comment by yinexum** [comment]
You have to set **true** for "handheld" in Init properties. Although was said that **true** is the default value, in the code **false** is the default.

in code;
`reset = !!options.reset; // true by default`
`handheld = !!options.handheld; // true by default`

but, _!!{}.undefined_ = **false**

**Comment by jdoleary** [comment]
Hi ElliGator,  This issue is fixed with the last merge.
