### ISSUE TITLE
init inside imagesloaded callback

### ISSUE THREAD

**Issue by grommas** [xtianmiller/emergence.js#7]
the plugin only triggers after first scroll movement when initialised inside the callback of [imagesloaded](https://imagesloaded.desandro.com/ ).

**Comment by grommas** [comment]
it works with emergence.engage() as a callback after loading the new site with ajax and imagesloaded, but it would be nice to have option to disable/enable or reinit.

**Comment by xtianmiller** [comment]
Thanks for the feedback. Per your solution, you can use emergence.engage() or emergence.disengage() to refire/disable.
