### ISSUE TITLE
Feature Request?

### ISSUE THREAD

**Issue by Uranbold** [xtianmiller/emergence.js#8]
Thanks for the lightweight and awesome plugin and I have 1 question?

Instead of changing the [data-emergence=visible] can we add the Class Toggle? Example:

I am using the [animate.css](https://daneden.github.io/animate.css/) and want to add some animate class to enter visible viewport.

Current condition is ok and I can customize the Classes but if I do this then I will duplicate this CSS file for  [data-emergence=visible] right?

I hope you can understand me :)

Thanks.

**Comment by Uranbold** [comment]
Also 1 more thing. If elements are in the Same Row then it's animated Instantly. I think it should delay between this 2 element.

It's becoming just like the waypoint ;)

**Comment by xtianmiller** [comment]
Hey Uranbold,

The idea behind the attributes is to give the markup more semantic meaning—didn't want to include classes to keep code light. You could use the callback function to add the animate.css classes. For example:

```javascript
emergence.init({
  reset: true,
  callback: function(element, state) {
    if (state === 'visible') {
      element.classList.add('animated','bounce');
    } else if (state === 'reset') {
      element.classList.remove('animated','bounce');
    }
  }
});
```

Regarding your second point, that's doable but would require more code and it really could be achieved with simply CSS nth-child and transition / animation delay.
